### ISSUE TITLE
Site is broken (404 not found)

### ISSUE THREAD

**Issue by mahdisml** [korlibs/korgw#16]
https://korlibs.soywiz.com/korgw/

Site is broken (404 not found)

**Comment by RezMike** [comment]
@mahdisml, where did you find this link? There is no korgw in the korlib's navigation menu

**Comment by mahdisml** [comment]
![image](https://user-images.githubusercontent.com/1758504/77249361-139cf300-6c5e-11ea-942a-609dbc469c83.png)
this place :)

**Comment by soywiz** [comment]
Now it points to an existing though uncomplete page
